# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib logKDE
#'
#'
NULL

epanechnikov <- function(x) {
    .Call('_logKDE_epanechnikov', PACKAGE = 'logKDE', x)
}

gaussian <- function(x) {
    .Call('_logKDE_gaussian', PACKAGE = 'logKDE', x)
}

laplace <- function(x) {
    .Call('_logKDE_laplace', PACKAGE = 'logKDE', x)
}

logistic <- function(x) {
    .Call('_logKDE_logistic', PACKAGE = 'logKDE', x)
}

triangular <- function(x) {
    .Call('_logKDE_triangular', PACKAGE = 'logKDE', x)
}

uniform <- function(x) {
    .Call('_logKDE_uniform', PACKAGE = 'logKDE', x)
}

KDE_e <- function(x, xi, h) {
    .Call('_logKDE_KDE_e', PACKAGE = 'logKDE', x, xi, h)
}

KDE_g <- function(x, xi, h) {
    .Call('_logKDE_KDE_g', PACKAGE = 'logKDE', x, xi, h)
}

KDE_lo <- function(x, xi, h) {
    .Call('_logKDE_KDE_lo', PACKAGE = 'logKDE', x, xi, h)
}

KDE_t <- function(x, xi, h) {
    .Call('_logKDE_KDE_t', PACKAGE = 'logKDE', x, xi, h)
}

KDE_la <- function(x, xi, h) {
    .Call('_logKDE_KDE_la', PACKAGE = 'logKDE', x, xi, h)
}

KDE_u <- function(x, xi, h) {
    .Call('_logKDE_KDE_u', PACKAGE = 'logKDE', x, xi, h)
}

logKDE <- function(input, support, h, method = "uniform") {
    .Call('_logKDE_logKDE', PACKAGE = 'logKDE', input, support, h, method)
}

