# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@importFrom Rcpp sourceCpp
#'@useDynLib logKDE
#'
NULL

logEpanechnikov <- function(x) {
    .Call('_logKDE_logEpanechnikov', PACKAGE = 'logKDE', x)
}

logGaussian <- function(x) {
    .Call('_logKDE_logGaussian', PACKAGE = 'logKDE', x)
}

logLaplace <- function(x) {
    .Call('_logKDE_logLaplace', PACKAGE = 'logKDE', x)
}

logLogistic <- function(x) {
    .Call('_logKDE_logLogistic', PACKAGE = 'logKDE', x)
}

logTriangular <- function(x) {
    .Call('_logKDE_logTriangular', PACKAGE = 'logKDE', x)
}

logUniform <- function(x) {
    .Call('_logKDE_logUniform', PACKAGE = 'logKDE', x)
}

KDE <- function(x, xi, h) {
    .Call('_logKDE_KDE', PACKAGE = 'logKDE', x, xi, h)
}

silverman <- function(x) {
    .Call('_logKDE_silverman', PACKAGE = 'logKDE', x)
}

#'@export
logKDE <- function(input, support, h, method = "logUniform") {
    .Call('_logKDE_logKDE', PACKAGE = 'logKDE', input, support, h, method)
}

